### ISSUE TITLE
n variables

### ISSUE THREAD

**Issue by Aurbo99** [keyone78/Ethernet-Cable-Tester-for-Pic-18f4550#1]
Thanks again for posting the code from your Youtube file.

I'm having great difficulty re-tracing your code with the same 'n' variable used throughout your files

in particular the 'void test_ethernet(void){' routine.

Any chance of you commenting in the code which 'n' value is being used at which point?

example;
for (int na=1;na<9;na++)
passResult[na]=single_modeTest(na); // test result load to array slots
for(int nb=1 ;nb<9;nb++) {  
if(passResult[na]=='F'){ // check the error connect to where.
for(int ck_line=1 ;ck_line<9;ck_line++)
if(connect_error(n,ck_line)!='X') {
lcd_Out_Cp(1,na+2, connect_error(na,ck_line) +48); // display the error connect to which pin
DelayMs(2);
}
else{
openline++;
if(openline==8) // if no error detect after tested all pin...
lcd_Out_Cp(1,n+2,'X'); //....it may be open line
}
}
else{
lcd_Out_Cp(1,na+2, na+48); // pass just display the pin no to LCD
}
}
for(int nc=0 ;nc<9;nc++) { // check for number of pass
lcd_Out_Cp(2,na+2, passResult[na] ); // dsiplay to lCD
if(passResult[na]=='P')
passNum++;
}

**Comment by keyone78** [comment]
Any chance of you commenting in the code which 'n' value is being used at which point?
Note\* you may want to add a input switch to pause at certain check point .

/// 1st check, the direct connection  --> single_modeTest();  start from 10
// example to check all direct wire 1 to 1 , 2  to 2 ... till 8 to 8

// after the all wire is checked
// result will pass to --> passResult [n]  array

//2nd  look into the passResult[n] array  if result is   'F' fail 
//   will proceed to check get more information 
// connect_error(n,ck_line)!='X',  
     if(passResult[n]=='F'){              /\* 2nd check*/   the wire is false 
     so it maybe the case that the wire connected to other wires  so test all the wire  example 1to 2, 1 to 2 ,1 to 3 .... till 1 to 8 
     after connect_error( n,ck_line)!='X'

```
 it will return  the wire actually connected to which other wire.
```

void test_ethernet(void){

```
unsigned char passResult[9]={'>',9,3,0,9,6,7,8};   // array of 8 slot 1 to 8
unsigned char passNum=0,openline=0;  // passNum indicate the number, openline 

 lcd_clear();                       // LCD clear
 lcd_Out(1,0,"No:");       // display "No:"
 DelayMs(10);                   // delay for 10 ms


for (int n=1;n<9;n++)                           
 passResult[n]=single_modeTest(n);      /* 1st check*/    // test result load to array slots  



 for(int n=1 ;n<9;n++) {                         

   if(passResult[n]=='F'){              /* 2nd check*/          // check the error connect to where.

    for(int ck_line=1 ;ck_line<9;ck_line++)

        if(connect_error(n,ck_line)!='X') {           /* 2.1  check*/                      

          lcd_Out_Cp(1,n+2, connect_error(n,ck_line) +48); // display the error connect to  which pin
          DelayMs(2);

         }   
        else{

        openline++;                          /* 3.1 */              //   wire open display x
           if(openline==8)     // if no error detect after tested all pin...
           lcd_Out_Cp(1,n+2,'X'); //....it may be open line   


        }
    }
  else{
    lcd_Out_Cp(1,n+2, n+48);  // pass just display the pin no to LCD


  }
}



 for(int n=0 ;n<9;n++)  {                   // check for number of  pass
 lcd_Out_Cp(2,n+2, passResult[n] );    // dsiplay to lCD
  if(passResult[n]=='P')
   passNum++;

 }

if(passNum==8)
  lcd_Out(2,11," Pass");

else
   lcd_Out(2,11," Fail");
```

  }

**Comment by Aurbo99** [comment]
I'm using MikroC, so the LCD and delay commands are a little different from your original code.

I changed the series of 'n' variables to 'an',bn','cn' to try to understand your looping methods

Could you confirm I made the correct changes to the 'n' variable

Thanks
Steve

void test_ethernet(void)
   {
    unsigned char passResult[9]={'>',9,3,0,9,6,7,8};                            // array of 8 slot 1 to 8
    unsigned char passNum=0,openline=0,ck_line=0;                               // passNum indicate the number, openline
    unsigned char an,bn,cn;
    Lcd_Out(1, 1, "Test cable");
    Delay_ms(1000);
    Lcd_Cmd(_LCD_CLEAR);
    Lcd_Out(1, 1,"No:");
       for(an=1;an<9;an++)                                                         // first check to see if all wires are connected 1-1,2-2 etc
          passResult[an]=single_modeTest(an);                                     // test result load to array slots
          for(bn=1;bn<9;bn++)
            {
             if(passResult[an]=='F')                                             // check the error connect to where.
               {
               for(ck_line=1 ;ck_line<9;ck_line++)
                  if(connect_error(an,ck_line)!='X')
                   {
                    Lcd_Out(1,an+2, connect_error(an,ck_line) +48);            // display the error connect to  which pin
                    Delay_ms(2);
                   }
                  else
                   {
                    openline++;
                    if(openline==8)     // if no error detect after tested all pin...
                    Lcd_Out(1,an+2,'X'); //....it may be open line
                   }
               }
              else
                 {
                 Lcd_Out(1,an+2,an+48);  // pass just display the pin no to LCD
                 }
            }
         for(cn=0;cn<9;cn++)                                                  // check for number of  pass
           {
           Lcd_Out(2,n+2, passResult[an] );    // dsiplay to lCD
              if(passResult[an]=='P')
              passNum++;
           }
      if(passNum==8)
         Lcd_Out(2,11," Pass");
         else
         Lcd_Out(2,11," Fail");
   }

**Comment by Aurbo99** [comment]
unsigned char passResult[9]={'>',9,3,0,9,6,7,8};   <--  is there a value missing?

**Comment by Aurbo99** [comment]
Keyone78

I've managed to convert nearly all of your code to MikroC,  only two issues remains,  getting the wire numbers to appear after "No:  and getting the "unsigned char connect_error(unsigned char seq_no, unsigned char testno)" routine to run correctly. 

Maybe its actually running, but the display after "No:" may be hiding the results.
[code]
sbit LCD_RS at LATA4_bit;                                                       //Lcd module connections
sbit LCD_EN at LATA5_bit;                                                       //Lcd module connections
sbit LCD_D4 at LATA0_bit;                                                       //Lcd module connections
sbit LCD_D5 at LATA1_bit;                                                       //Lcd module connections
sbit LCD_D6 at LATA2_bit;                                                       //Lcd module connections
sbit LCD_D7 at LATA3_bit;                                                       //Lcd module connections
sbit LCD_RS_Direction at TRISA4_bit;                                            //Lcd module connections
sbit LCD_EN_Direction at TRISA5_bit;                                            //Lcd module connections
sbit LCD_D4_Direction at TRISA0_bit;                                            //Lcd module connections
sbit LCD_D5_Direction at TRISA1_bit;                                            //Lcd module connections
sbit LCD_D6_Direction at TRISA2_bit;                                            //Lcd module connections
sbit LCD_D7_Direction at TRISA3_bit;                                            //Lcd module connections
Lcd_Init();

// output PORTD cable define
#define RJD                  LATD
#define RJD_dir              TRISD
#define RJD_1                LATD.RD0
#define RJD_2                LATD.RD1
#define RJD_3                LATD.RD2
#define RJD_4                LATD.RD3
#define RJD_5                LATD.RD4
#define RJD_6                LATD.RD5
#define RJD_7                LATD.RD6
#define RJD_8                LATD.RD7

// input port cable define
#define RJC                  LATC
#define RJC_dir              TRISC
#define RJC_test             PORTC
#define RJC_1                LATC0
#define RJC_2                LATC1
#define RJC_3                LATC2
#define RJC_4                LATC3
#define RJC_5                LATC4
#define RJC_6                LATC5
#define RJC_7                LATC6
#define RJC_8                LATC7

#define flash_all_zero       0x00
#define dir_out              0x00
#define dir_in               0xFF
#define all_high             dir_in
#define pass                 'P';                                               //  indicate Pass
#define fail                 'F';                                               // indicate fail
#define RUN_1                1
void test_cable(void);
void DelaybySec(unsigned char cnt);
void main_startUp(void);
unsigned char str_Atest_con(void);
void flash_RJD(void);
unsigned char single_modeTest(unsigned char );
void pinToHigh_Test(unsigned char num);
unsigned char connect_error(unsigned char seq_no,unsigned char testno);
void main(void)
   {
   main_startUp();                                                              // initial pin port
   test_cable();
   Delay_ms(250);
   }
void test_cable(void)
   {
    unsigned char passResult[9]={'>',9,3,0,9,6,7,8};                            // array of 8 slot 1 to 8
    unsigned char passNum=0,openline=0,ck_line=0;                               // passNum indicate the number, openline
    unsigned char n;
    char bport[4]="";
    char cport[4]="";
    Lcd_Out(1, 1,"Test cable");
    Delay_ms(1000);
    Lcd_Cmd(_LCD_CLEAR);
    Lcd_Out(1,1,"No:");
       for(n=1;n<9;n++)
          passResult[n]=single_modeTest(n);                                     // test result load to array slots
          ByteToStr(n, bport);                                                                     // first check to see if all wires are connected 1-1,2-2 etc
          for(n=1;n<9;n++)
            { 
             ByteToStr(n, cport);
             Lcd_Out(1,n+3,Ltrim(cport));
             if(passResult[n]=='F')                                             // check the error connect to where.
               {
               Lcd_Chr(1,n+3,'X');
               for(ck_line=1;ck_line<9;ck_line++)
                  if(connect_error(n,ck_line)!='X')
                   {
                   //ByteToStr(ck_line, cport);
                   //Lcd_Out(1,n+3,Ltrim(cport));
                   //Lcd_Out(1,n+3,(connect_error(n,ck_line) +48));               // display the error connect to  which pin
                   }
                  else
                   {
                    openline++;
                    if(openline==8)                                             // if no error detect after tested all pin...
                    Lcd_Chr(1,n+3,'X'); //Delay_ms(300);                        //....it may be open line
                   }
               }
              else
                 {
                 ByteToStr(n+48, cport);
                 Lcd_Out(2,n+3,Ltrim(cport));
                 //Lcd_Out(2,n+3,(n+48));                                         // pass just display the pin no to LCD
                 }
           }  
         for(n=0;n<9;n++)                                                       // check for number of  pass
           {
           Lcd_Chr(2,n+3, passResult[n] );                                      // dsiplay to lCD
              if(passResult[n]=='P')
              passNum++;
           }
      if(passNum==8)
         Lcd_Out(2,12,":Pass");
         else
         Lcd_Out(2,12,":Fail");
   }
void main_startUp(void)
  {
    ADCON0 = 0;
    ADCON1 = 0X0F;                                                              //All port in digital mode
    CMCON  = 7;                                                                 //comparators off
    PORTA = 0x00;
    TRISA = 0x00;
    PORTB = 0x00;
    TRISB = 0x00;
    PORTC = 0x00;
    TRISC = 0x00;
    LATC  = 0x00;
    PORTD = 0x00;
    TRISD = 0x00;
    PORTE = 0x00;
    TRISE = 0x00;
    Lcd_Init();                                                                 // LCD  initization
    Lcd_Cmd(_LCD_CURSOR_OFF);
    Lcd_Cmd(_LCD_CLEAR);
    RJD = flash_all_zero;
    RJD_dir = dir_out;                                                          // Ethernet A1 to A3
    RJD = all_high;
    RJC_dir = dir_in;                                                           // port B is input port
    RJC = flash_all_zero;
   }
void flash_RJD(void)                                                            // to flash one time at port A
   {
    RJD=flash_all_zero;
    Delay_ms(5);
    RJD=all_high;
   }
unsigned char str_Atest_con(void)
   {
    unsigned char num=0;
    while (num<5)
      {                                                                         // Test for continualty in all 8 wires (5 times)
       Delay_ms(2);
       flash_RJD();
       if(PORTC==0xff)
          num++;
       else
        return fail;
      }
        return pass;
   }

void RJD_low(void)
   {
    LATD = flash_all_zero;
   }

void pinToHigh_Test(unsigned char num)
   {
   RJD_low();                                                                   // All pin on enthernet A to  low,   clear all
   Delay_ms(5);                                                                 // delay 2 ms
   switch (num)
      {                                                                         // pin to '1' on  indiviual pin
       case 1:RJD_1=RUN_1; break;
       case 2:RJD_2=RUN_1; break;
       case 3:RJD_3=RUN_1; break;
       case 4:RJD_4=RUN_1; break;
       case 5:RJD_5=RUN_1; break;
       case 6:RJD_6=RUN_1; break;
       case 7:RJD_7=RUN_1; break;
       case 8:RJD_8=RUN_1; break;
       default: break;
      }
       Delay_ms(5);
   }
// FIRST TEST = CONTINUITY
unsigned char single_modeTest(unsigned char seq_no)                             // ethernet A (OUT) ---> ethernet B (IN)
   {
    unsigned char setTestbyte[9]={0x00,0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80};
    pinToHigh_Test(seq_no);                                                     // active high on selected pin for (ethernet port A)
    if(RJC_test==setTestbyte[seq_no])                                           // check for result at enthernet port B
       {
       return pass;
       }                                                                        // if port B result is same as setTestbyte  return "P" , pass
    else
       {
       return fail;                                                             // else fail
       }
   }
// for checking wire connect to which pin rather than the correct one
unsigned char connect_error(unsigned char seq_no, unsigned char testno)
   {
   unsigned char setTestbyte[9]={0x00,0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80};
   pinToHigh_Test(seq_no);                                                      // active high on selected pin for (ethernet port A)
   if(RJC_test==setTestbyte[testno])
     return testno;
     else
     {
      return 'X';
     }
   }
[/code]

**Comment by keyone78** [comment]
unsigned char passResult[9]={'>',9,3,0,9,6,7,8}; <-- is there a value missing?

this can be any value , you can initialize to all 0.

**Comment by keyone78** [comment]
I've managed to convert nearly all of your code to MikroC, only two issues remains, getting the wire numbers to appear after "No: and getting the "unsigned char connect_error(unsigned char seq_no, unsigned char testno)" routine to run correctly. 

->> try to insert delay in your code .... different hardware may have difference speed. 

---> in line  73 to 75  
as my code without { }
for(n=1;n<9;n++) 
    passResult[n]=single_modeTest(n); // test result load to array slots
    ByteToStr(n, bport); // first check to see if all wires are connected 1-1,2-2 etc
// if ByteToStr(n, bport);  is associate with loop then { } within it is not n is after 8 

## 

## in your code , may be the complier  you using  cannot proceed .  the unsigned char in " unsigned char connect_error(unsigned char seq_no, unsigned char testno)" is 0 to 8 so to print to LCD require to change to AscII code which is add 48, or ad '0' (in unsigned char) . 

can you print out normal letter in LCD .  
//Lcd_Out(1,n+3,(connect_error(n,ck_line) +48)); // display the error connect to which pin

-- try insert Lcd_Out(2,1,"ok") and LcD_Out(2,1,"notok"); so you know where mistake ocurr
